import type { PlanDefinition } from "./plan.types";

/**
 * Data comercial oficial do lançamento.
 * A promoção vale, no horário de São Paulo, até o fim de 30/06/2027.
 */
export const LAUNCH_PROMOTION_END_DATE = "2027-06-30";

/**
 * Regra anual-base: o cliente paga o equivalente a 10 meses e usa 12.
 * Isso representa aproximadamente 16,67% de desconto e permanece dentro
 * da faixa comercial acordada de 15% a 20%.
 */
const ANNUAL_MONTHS_CHARGED = 10;

export const planCatalog: readonly PlanDefinition[] = [
  {
    slug: "free",
    name: "Free",
    description:
      "Três meses para organizar os primeiros clientes e processos antes de escolher um plano pago.",
    users: 1,
    oabs: 1,
    clientsLimit: 10,
    registeredProcessLimit: 10,
    monitoredProcessLimit: 10,
    storageLimitGb: 1,
    freeMonths: 3,
    pricing: {
      launchMonthly: 0,
      standardMonthly: 0,
      annualMonthsCharged: 0,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "djen.monitoring",
      "publications.workflow",
    ],
    publicLaunchFeatures: [
      "1 usuário e 1 OAB cadastrada",
      "Até 10 clientes",
      "Até 10 processos cadastrados",
      "Agenda, tarefas e prazos manuais",
      "Documentos básicos e publicações do DJeN dentro do Jurisportal",
      "Sem e-mail de publicações, resumos, relatórios ou IA",
    ],
    internalAi: { monthlyUnits: 0 },
  },
  {
    slug: "essencial",
    name: "Essencial",
    description:
      "A porta de entrada para o advogado individual organizar a rotina e receber as automações jurídicas essenciais.",
    users: 1,
    oabs: 1,
    clientsLimit: "unlimited",
    registeredProcessLimit: 100,
    monitoredProcessLimit: 100,
    storageLimitGb: 10,
    pricing: {
      launchMonthly: 79.99,
      standardMonthly: 99.99,
      annualMonthsCharged: ANNUAL_MONTHS_CHARGED,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "petitionTemplates.basic",
      "finance.basic",
      "djen.monitoring",
      "notifications.email",
      "publications.workflow",
      "reports.basic",
    ],
    publicLaunchFeatures: [
      "1 usuário e 1 OAB",
      "Clientes ilimitados e até 100 processos",
      "Publicações e intimações do DJeN",
      "Alertas por e-mail",
      "Agenda, prazos, tarefas e fluxo de revisão de prazo",
      "Financeiro jurídico básico",
      "Modelos e documentos",
      "Relatórios básicos",
    ],
    internalAi: { monthlyUnits: 0 },
  },
  {
    slug: "estrategico",
    name: "Estratégico",
    description:
      "Para quem já precisa de equipe, mais OABs e um fluxo mais confortável de publicações e intimações.",
    users: 2,
    oabs: 2,
    clientsLimit: "unlimited",
    registeredProcessLimit: 250,
    monitoredProcessLimit: 250,
    storageLimitGb: 20,
    featured: true,
    inheritedFrom: "Essencial",
    pricing: {
      launchMonthly: 129,
      standardMonthly: 179,
      annualMonthsCharged: ANNUAL_MONTHS_CHARGED,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "petitionTemplates.basic",
      "finance.basic",
      "djen.monitoring",
      "notifications.email",
      "publications.workflow",
      "reports.basic",
      "team.members",
      "team.activity",
      "audit.full",
      "communications.clientEmail",
    ],
    publicLaunchFeatures: [
      "2 usuários, 2 OABs e até 250 processos",
      "Gestão de equipe e níveis de acesso",
      "Fluxo ampliado de publicações e intimações",
      "Relatório de atividade da equipe",
      "Auditoria completa",
      "Atualização manual ao cliente por e-mail",
      "Sem recursos de IA",
    ],
    internalAi: { monthlyUnits: 0 },
  },
  {
    slug: "premium",
    name: "Premium",
    description:
      "O primeiro plano com inteligência aplicada à gestão, comunicação e tratamento da rotina jurídica.",
    users: 3,
    oabs: 3,
    clientsLimit: "unlimited",
    registeredProcessLimit: 500,
    monitoredProcessLimit: 500,
    storageLimitGb: 50,
    inheritedFrom: "Estratégico",
    pricing: {
      launchMonthly: 179,
      standardMonthly: 249,
      annualMonthsCharged: ANNUAL_MONTHS_CHARGED,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "petitionTemplates.basic",
      "finance.basic",
      "djen.monitoring",
      "notifications.email",
      "publications.workflow",
      "reports.basic",
      "reports.advanced",
      "team.members",
      "team.activity",
      "audit.full",
      "communications.clientEmail",
      "ai.publicationSummary",
      "ai.explicitDateExtraction",
      "ai.clientUpdate",
      "ai.managementSummary",
    ],
    publicLaunchFeatures: [
      "3 usuários, 3 OABs e até 500 processos",
      "IA para resumo de publicações e intimações",
      "IA para localizar datas expressamente informadas",
      "Resumo de atualização ao cliente com revisão do advogado",
      "Resumo inteligente de gestão",
      "Relatórios avançados",
    ],
    internalAi: { monthlyUnits: 500 },
  },
  {
    slug: "executivo",
    name: "Executivo",
    description:
      "Para escritórios que precisam de maior capacidade e automações de comunicação mais amplas.",
    users: 5,
    oabs: 5,
    clientsLimit: "unlimited",
    registeredProcessLimit: 1000,
    monitoredProcessLimit: 1000,
    storageLimitGb: 100,
    inheritedFrom: "Premium",
    pricing: {
      launchMonthly: 349,
      standardMonthly: 449,
      annualMonthsCharged: ANNUAL_MONTHS_CHARGED,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "petitionTemplates.basic",
      "finance.basic",
      "djen.monitoring",
      "notifications.email",
      "publications.workflow",
      "reports.basic",
      "reports.advanced",
      "team.members",
      "team.activity",
      "audit.full",
      "communications.clientEmail",
      "ai.publicationSummary",
      "ai.explicitDateExtraction",
      "ai.clientUpdate",
      "ai.managementSummary",
      "communications.whatsapp",
      "calendar.google",
    ],
    publicLaunchFeatures: [
      "5 usuários, 5 OABs e até 1.000 processos",
      "Franquia interna ampliada de IA",
      "Preparado para automações de comunicação avançadas",
      "Recursos avançados de gestão e relatórios",
      "Integrações de maior capacidade quando validadas",
    ],
    internalAi: { monthlyUnits: 2500 },
  },
  {
    slug: "alta-corte",
    name: "Alta Corte",
    description:
      "Para operações jurídicas maiores que precisam da maior capacidade, prioridade e integrações avançadas.",
    users: 10,
    oabs: 10,
    clientsLimit: "unlimited",
    registeredProcessLimit: 2000,
    monitoredProcessLimit: 2000,
    storageLimitGb: 200,
    inheritedFrom: "Executivo",
    pricing: {
      launchMonthly: 550,
      standardMonthly: 750,
      annualMonthsCharged: ANNUAL_MONTHS_CHARGED,
    },
    capabilities: [
      "clients.basic",
      "processes.basic",
      "agenda.basic",
      "tasks.basic",
      "deadlines.manual",
      "documents.basic",
      "petitionTemplates.basic",
      "finance.basic",
      "djen.monitoring",
      "notifications.email",
      "publications.workflow",
      "reports.basic",
      "reports.advanced",
      "team.members",
      "team.activity",
      "audit.full",
      "communications.clientEmail",
      "ai.publicationSummary",
      "ai.explicitDateExtraction",
      "ai.clientUpdate",
      "ai.managementSummary",
      "communications.whatsapp",
      "calendar.google",
      "processPortfolio.oabImport",
      "processMonitoring.external",
      "courtCredentials",
      "courtDocuments",
    ],
    publicLaunchFeatures: [
      "Até 10 usuários, 10 OABs e 2.000 processos",
      "Maior franquia interna de IA",
      "Maior capacidade operacional",
      "Prioridade de suporte e implantação",
      "Preparado para integrações judiciais avançadas",
    ],
    internalAi: { monthlyUnits: 10000 },
  },
] as const;
