"use client";
import { useState } from "react";
import styles from "./PetitionTemplates.module.css";

type ProcessOption = { id: string; internalCode: string; cnjFormatted: string; subject: string | null; clients: { client: { id: string; name: string; tradeName: string | null } }[] };
type ClientOption = { id: string; name: string; tradeName: string | null; taxIdRaw: string };

export function PetitionDraftGenerator({ source, templateId, officialSlug, processes, clients }: { source: "OFFICIAL"|"OFFICE"; templateId?: string; officialSlug?: string; processes: ProcessOption[]; clients: ClientOption[] }) {
  const [processId,setProcessId]=useState(""); const [clientId,setClientId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [content,setContent]=useState(""); const [unresolved,setUnresolved]=useState<string[]>([]); const [generationId,setGenerationId]=useState(""); const [saveState,setSaveState]=useState<""|"saving"|"saved">(""); const [exporting,setExporting]=useState(false);
  async function generate(){ setBusy(true); setError(""); setSaveState(""); try { const response=await fetch("/api/petition-templates/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source,templateId,officialSlug,processId:processId||null,clientId:clientId||null})}); const data=await response.json().catch(()=>({})) as {error?:string;renderedContent?:string;unresolvedVariables?:string[];generation?:{id:string}}; if(!response.ok){setError(data.error==="PETITION_CLIENT_NOT_LINKED_TO_PROCESS"?"O cliente escolhido não está vinculado ao processo selecionado.":"Não foi possível gerar o rascunho."); return;} setContent(data.renderedContent??""); setGenerationId(data.generation?.id??""); setUnresolved(data.unresolvedVariables??[]); } finally {setBusy(false);} }
  async function save(){ if(!generationId||!content.trim())return; setSaveState("saving"); setError(""); const response=await fetch(`/api/petition-templates/generations/${generationId}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({content})}); if(!response.ok)setError("Não foi possível salvar a revisão final."); else setSaveState("saved"); }
  async function exportPdf(){ if(!generationId||!content.trim())return; setExporting(true); setError(""); try { const response=await fetch(`/api/petition-templates/generations/${generationId}/export-pdf`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content})}); if(!response.ok){setError("Não foi possível gerar o PDF."); return;} const blob=await response.blob(); const disposition=response.headers.get("content-disposition")??""; const match=disposition.match(/filename="([^"]+)"/); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=match?.[1]??"documento.pdf"; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); setSaveState("saved"); } finally {setExporting(false);} }
  return <section className={styles.generator}>
    <div><span className={styles.eyebrow}>Gerar documento</span><h2>Preencher, revisar e exportar</h2><p>Selecione processo e/ou cliente. O Jurisportal resolve as variáveis no servidor. Antes do uso jurídico, revise livremente o texto final.</p></div>
    {error?<div className={styles.error}>{error}</div>:null}
    <div className={styles.generatorGrid}>
      <div className={styles.field}><label>Processo, opcional</label><select value={processId} onChange={(e)=>setProcessId(e.target.value)}><option value="">Nenhum processo</option>{processes.map((process)=><option key={process.id} value={process.id}>{process.internalCode} · {process.cnjFormatted} · {process.clients[0]?.client.tradeName||process.clients[0]?.client.name||process.subject||"Sem cliente"}</option>)}</select></div>
      <div className={styles.field}><label>Cliente, opcional</label><select value={clientId} onChange={(e)=>setClientId(e.target.value)}><option value="">Usar cliente principal do processo</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.tradeName||client.name} · {client.taxIdRaw}</option>)}</select></div>
    </div>
    <div className={styles.actions}><button type="button" className={styles.primaryButton} disabled={busy} onClick={generate}>{busy?"Gerando...":"Gerar rascunho"}</button></div>
    {unresolved.length?<div className={styles.notice}><strong>Há dados que não puderam ser preenchidos automaticamente.</strong><ul className={styles.warningList}>{unresolved.map((token)=><li key={token}>{token}</li>)}</ul></div>:null}
    {content?<><div className={styles.field}><label>Documento final editável</label><textarea className={styles.finalEditor} value={content} onChange={(e)=>{setContent(e.target.value);setSaveState("");}} /><small>Edite o que for necessário. O PDF será criado exatamente a partir deste texto.</small></div><div className={styles.actions}><button type="button" className={styles.secondaryButton} disabled={saveState==="saving"} onClick={save}>{saveState==="saving"?"Salvando...":saveState==="saved"?"Revisão salva":"Salvar revisão"}</button><button type="button" className={styles.primaryButton} disabled={exporting} onClick={exportPdf}>{exporting?"Gerando PDF...":"Baixar PDF A4"}</button></div><small>Confira o conteúdo antes de enviar ao cliente ou usar o documento em outro sistema.</small></>:null}
  </section>;
}
