ALTER TABLE "petition_generation"
  ADD COLUMN "finalContent" TEXT,
  ADD COLUMN "lastEditedAt" TIMESTAMP(3),
  ADD COLUMN "exportedAt" TIMESTAMP(3),
  ADD COLUMN "exportCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
